FROM almalinux
RUN yum install nginx -y
RUN rm -rf usr/share/nginx/html/index.html
ADD https://github.com/techworldwithsiva/dockerfiles/tree/master/COPY/qi /usr/share/nginx/html/
CMD [ "nginx","-g","daemon off;" ]
